name: Pylint

on:
  pull_request:
    branches:
    - master

jobs:
  Pylint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
      - run: pip install pylint  # -r requirements.txt
      - run: pylint **/*.py

